---
- name: Start ec2 instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
      instance_ids:
          - 'i-043f537b91d7369d7'
      region: us-west-1
  tasks:
    - name: Start the feature instances
    ec2:
    instance_ids: '{{ instance_ids }}'
    region: '{{ region }}'
    state: running
    wait: True
